### ISSUE TITLE
Failing node-gyp configure/rebuild results in successful installation

### ISSUE THREAD

**Issue by jessecstewart** [blackbeam/poppler-simple#13]
When running `npm install poppler-simple`, if the node-gyp compilation fails the npm install still succeeds. This is undesirable because it is hard to tell what went wrong (especially if it fails as part of a lengthy `npm install`). The problem appears to be these few lines --
https://github.com/blackbeam/poppler-simple/blob/master/package.json#L14
Where `exit 0` should probably be `exit 1`.

**Comment by blackbeam** [comment]
Thanks!
