### ISSUE TITLE
can not install on mac node 6.x and 8.x

### ISSUE THREAD

**Issue by Pana** [blackbeam/poppler-simple#19]
<img width="1013" alt="screen shot 2017-09-09 at 14 23 58" src="https://user-images.githubusercontent.com/552081/30237764-4de733f2-94fe-11e7-8897-92f7d57240fc.png">

**Comment by blackbeam** [comment]
Hi!
Which c++ compiler do you use?

**Comment by Pana** [comment]
I am using xcode command line tool, with gcc --version i got this 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by blackbeam** [comment]
I've just published v0.2.8 of poppler-simple. It should work with poppler >= 0.55.0.
Could you please install latest version using `npm --verbose install poppler-simple` and post output here?

**Comment by Pana** [comment]
I can success install it now, thanks

**Comment by Pana** [comment]
When i install it on centos i got this bug

<img width="1214" alt="screen shot 2017-09-12 at 18 02 20" src="https://user-images.githubusercontent.com/552081/30320307-dca913e6-9777-11e7-8afe-bedd3f722b88.png">

**Comment by Pana** [comment]
I have install poppler with cmd "yum install poppler"

**Comment by blackbeam** [comment]
In linux distros `poppler-version.h` is usually in packet called like [`poppler-cpp-devel`](https://centos.pkgs.org/7/centos-x86_64/poppler-cpp-devel-0.26.5-16.el7.x86_64.rpm.html) or similar.

**Comment by Pana** [comment]
I got it, thanks very much
