### ISSUE TITLE
Package poppler was not found in the pkg-config search path

### ISSUE THREAD

**Issue by msageryd** [blackbeam/poppler-simple#22]
I'm not able to build poppler-simple. I've tried a lot of combos.

- Node 6, 8, 10
- OSX
- Debian (via docker)
- Alpine (via Docker)

Poppler installs fine in all the above scenarios (using **brew**, **apt-get** and **apk** respectively), but `npm install` gives the following error. 

Does anyone have any clue? I did get poppler-simple to work on another computer (not available anymore). I'd really like to get this running in a Docker container.

```
Perhaps you should add the directory containing `poppler.pc'
to the PKG_CONFIG_PATH environment variable
Package 'poppler', required by 'virtual:world', not found
gyp: Call to 'pkg-config --libs poppler' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.9.93-linuxkit-aufs
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure"
gyp ERR! cwd /tmp/node_modules/poppler-simple
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by blackbeam** [comment]
Hi.
Please try to run `pkg-config --libs poppler` in your environment and inspect the output.

I found some random ubuntu for an example and got the following output:

```
~$ LANG=C pkg-config --libs poppler
The program 'pkg-config' can be found in the following packages:
 * pkg-config
 * pkgconf
Try: sudo apt install <selected package>
```

i.e. `pkg-config` is not installed, but `pkg-config` it required for build script to work.

**Comment by msageryd** [comment]
Here is the Dockerfile. I've stripped it down to the essentials about poppler. I now realise that this has nothing with poppler-simple to do. But I'm hoping someone here has any clue anyway.

N.B. I also tried with `FROM alpine` to ensure that node doesn't interfere. Same result..

```
FROM node:10-alpine
RUN apk --update --upgrade add pkgconfig python poppler
RUN pkg-config --libs poppler
```

The result is:
```
Step 4/4 : RUN pkg-config --libs poppler
 ---> Running in 66f5ff01a56f
Package poppler was not found in the pkg-config search path.
Perhaps you should add the directory containing `poppler.pc'
to the PKG_CONFIG_PATH environment variable
```

**Comment by blackbeam** [comment]
Looks like poppler pc files is in poppler-dev package.
https://pkgs.alpinelinux.org/contents?branch=edge&name=poppler-dev&arch=aarch64&repo=main

**Comment by blackbeam** [comment]
There is a lot of flood during build but looks like everything works with `node:8-alpine`.
Please swith to it if possible. I will schedule update for node v10.

**Comment by msageryd** [comment]
Thanks again.
That's great news. I tried all Node versions and assumed the same error due to the flood of bright red messages. But now I see that the actual outcome is "success" on Node 8.

Thank you very much for your help. Would you like me to send you a PR with a small write-up on installing on Docker? I think it could help many others to get going wit poppler-simple.

**Comment by blackbeam** [comment]
> Would you like me to send you a PR with a small write-up on installing on Docker?

Great idea!
