### ISSUE TITLE
Extracting page-index

### ISSUE THREAD

**Issue by msageryd** [blackbeam/poppler-simple#24]
Is there a way to extract a page-index from the PDF file? I know that other libraries can do this, but I'd prefer keeping the dependency-count down if possible.

**Comment by blackbeam** [comment]
Did you mean page number like [here](https://github.com/blackbeam/poppler-simple/blob/master/test/test.js#L220)?

**Comment by msageryd** [comment]
Yeah, great!
Sorry for not reading trough the tests. I glanced through the C code, but nothing jumped out to me. Should have heded straight to tests.

**Comment by blackbeam** [comment]
I've got typescript definitions somewhere.
Looks like i need to find and publish them as a documentation..

**Comment by blackbeam** [comment]
Documentation is now available in form of typescript definitions.
It is actual for [v0.7.0](https://github.com/blackbeam/poppler-simple/releases/tag/v0.7.0)
But please beware of breaking change in v0.7.0
