### ISSUE TITLE
Output to SVG?

### ISSUE THREAD

**Issue by msageryd** [blackbeam/poppler-simple#26]
I think that Poppler uses on Cairo under the hood, is that right? If that's the case I suppose one could extract SVG graphics from a PDF with Poppler (as with the utility pdftocairo)?

Would it be an easy addition to poppler-simple to also offer svg as output format?

**Comment by blackbeam** [comment]
poppler-simple uses splash which is a part of poppler afaik and splash have no SVG support.
It would be nice to support svg output but there is a long-standing blocker: https://gitlab.freedesktop.org/poppler/poppler/issues/83

**Comment by msageryd** [comment]
Ok, thanks.
It would have been great to be able to do all the work in buffers/strems and not hit the disk. But I guess I’ll have to resort to calling pdf2cairo via childprocesses and keep the files at the local disk while extracting svg data.


Sent from my iPad

On 21 Nov 2018, at 17:58, Anatoly I <notifications@github.com<mailto:notifications@github.com>> wrote:


poppler-simple uses splash which is a part of poppler afaik and splash have no SVG support.
It would be nice to support svg output but there is a long-standing blocker: https://gitlab.freedesktop.org/poppler/poppler/issues/83
