### ISSUE TITLE
Throw error on corrupt PDF

### ISSUE THREAD

**Issue by mgartner** [blackbeam/poppler-simple#4]
I've written some tests for code that uses poppler-simple to make sure it can gracefully handle corrupt PDF files. I'd tried surrounding `new PopplerDocument()` in a `try/catch` to catch an error for a bad PDF, but poppler-simple doesn't seem to throw any errors if the document is bad. Is there anyway to catch an error for a corrupt PDF?

**Comment by blackbeam** [comment]
Yes it is:
```
> try{ new p.PopplerDocument('file:///tmp/adb.log') } catch(e) { console.log("Exception", e);}
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Exception [Error: Couldn't open file - damaged.]
undefined
```

But it highly depends on poppler itself. I know that it just crashes on some bad pdfs.
Here is the logic: [PopplerDocument.cc:117](https://github.com/blackbeam/poppler-simple/blob/master/src/NodePopplerDocument.cc#L117)

Can you give me your corrupt pdf?

**Comment by mgartner** [comment]
Ahhh, thanks. I was able to corrupt my PDF enough so that is crashed.

Poppler is pretty resilient... I thought adding in some random characters near the top of the file would throw off the data in the XREF table and Poppler wouldn't be able to parse it, but it still did. Crazy...

Btw, I'm loving `poppler-simple`! Came in handy for https://github.com/lob/calipers. :+1:
