### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by Kukiwon** [blackbeam/poppler-simple#44]
When running `npm i` it fails to install. I'm using Node v17.1.0 on Apple Silicon (macOS). See attached screenhshot:

<img width="1603" alt="Schermafbeelding 2021-11-17 om 09 12 08" src="https://user-images.githubusercontent.com/3714353/142160996-8c125fef-6bd1-46cf-be3d-78ec45f153a2.png">

Do you have any idea why this is failing?

Thanks!

**Comment by blackbeam** [comment]
Hi. Year, it's because of a breaking change in poppler-21.11.0. Namely [this one](https://cgit.freedesktop.org/poppler/poppler/commit/?id=03f80c64305157fbebff73cd57f582086e2cafdf).

**Comment by Kukiwon** [comment]
Thanks for your quick reply @blackbeam. I downgraded to poppler-21.10.0 and now it works! Here's how I did that for anyone else having this issue:

Uninstall current version of poppler first, then:

`url -O https://raw.githubusercontent.com/Homebrew/homebrew-core/b63945a86fab60915b318e8176e1c394041e4b3f/Formula/poppler.rb && brew install ./poppler.rb`

**Comment by blackbeam** [comment]
Should be resolved in [v0.10.3](https://github.com/blackbeam/poppler-simple/releases/tag/v0.10.3)
