### ISSUE TITLE
String is thrown instead of an Error

### ISSUE THREAD

**Issue by mgartner** [blackbeam/poppler-simple#6]
Due to the recent changes to [this line](https://github.com/blackbeam/poppler-simple/blob/2abbdd43a0fff1cefd4b189709fd5e9a60319abc/src/NodePopplerDocument.cc#L153) for Node v0.12 support, when supplying a damaged PDF a string is thrown instead of an error. It used to be an instance of an Error, which I think is more correct.

**Comment by blackbeam** [comment]
Ahh.. What a stupid mistake.
Anyway, fix published as 0.1.10.

**Comment by mgartner** [comment]
Thanks! :+1:
